[package]
name = "testh"
version = "0.1.0"
authors = ["Jan-Erik Rediger <janerik@fnordig.de>"]

[dependencies]
clippy = {version = "<0.1.0", optional = true}

[lib]
name = "testh"
path = "src/lib.rs"
plugin = true
